baseURL = "https://drawline.design"
copyright = "All rights reserved."
disqusshortname = ""
languagecode = "ja"
paginate = 10
pluralizelisttitles = false
theme = "hugo-theme-dd"
title = "nakajima nobuhiro"
canonifyurls = true

[[menu.main]]
identifier = "Home"
name = "home"
url = "/"
weight = 6
[[menu.main]]
identifier = "Profile"
name = "profile"
url = "/profile"
weight = 5
[[menu.main]]
identifier = "Portfolio"
name = "portfolio"
url = "/portfolio"
weight = 4
[[menu.main]]
identifier = "Etude"
name = "etude"
url = "/etude"
weight = 3

[params]
author = "Nakajima Nobuhiro"
authorlocation = "Tokyo, Japan"
authorWebSite = "https://drawline.design"
authorbio = "2D/3D Designer, Director"
cover = "images/cover_polenord.jpg"
description = "portfolio 2021"
googleAnalyticsUserID = ""
hideHUGOSupport = false
logo = "images/logo.png"
indexlogo = "images/logo.svg"
twitterName = "xinpak"
facebookName = "xinpak"
email = "drawline.dzn@gmail.com"
hjsStyle = "default"
coverText = "Rendering by : Substance Painter"


[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[taxonomies]
tag = "tags"
category = "categories"
