baseURL = "https://drawline.design"
copyright = "All rights reserved."
disqusshortname = ""
languagecode = "jp"
paginate = 10
pluralizelisttitles = false
theme = "hugo-theme-dd"
title = "drawline.design"
canonifyurls = true

[[menu.main]]
identifier = "Home"
name = "Home"
url = "/"
weight = 6
[[menu.main]]
identifier = "Development"
name = "Game Develop"
url = "/develop"
weight = 5
[[menu.main]]
identifier = "ui"
name = "UI"
url = "/ui"
weight = 4
[[menu.main]]
identifier = "Web"
name = "Web design"
url = "/web"
weight = 3
[[menu.main]]
identifier = "Misc"
name = "Misc"
url = "/misc"
weight = 2
[[menu.main]]
identifier = "Study"
name = "Study"
url = "/Study"
weight = 1

[params]
author = "Nakajima Nobuhiro"
authorlocation = "Tokyo, Japan"
authorWebSite = "https://drawline.design"
authorbio = "2D/3D Designer, Director"
cover = "images/cover_polenord.jpg"
description = "PORTFOLIO 2021"
googleAnalyticsUserID = "UA-117426393-1"
hideHUGOSupport = true
metadescription = "中嶋信博 ポートフォリオ"
logo = "images/logo.png"
indexlogo = "images/logo.svg"
twitterName = "xinpak"
facebookName = "xinpak"
email = "n.nakajima@drawline.design"
hjsStyle = "default"
coverText = "Rendering by : Modo"
frontPageSections = ["portfolio","study"]

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[taxonomies]
tag = "tags"
category = "categories"
